service: scream-in-despair

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${opt:region, 'us-east-2'}
  profile: ${env:AWS_PROFILE}
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  timeout: 15

plugins:
  - serverless-dotenv-plugin
  - serverless-offline-scheduler
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0

functions:  
  tweetSchedule:
    handler: src/services/tweetSchedule.handler
    description: Function to tweet a shout message based on a schedule
    events:
      - schedule: cron(20 * * * ? *)
